#!/usr/bin/env bash
# html-report :: deploy.sh — deploy report to user's workspace
#
# Usage:
#   deploy.sh <report-dir> <output-dir>
#
# Copies <report-dir> into <output-dir>/<name>/, then:
#   1. Removes any .md files (plan.md etc. should not be in report dir, but just in case)
#   2. Removes unreferenced JS files from _shared/js/
#   3. Verifies all .html files contain <!-- Generated by Trae Work -->
#
# Output structure:
#   <output-dir>/<name>/
#   ├── <name>.html         (must contain <!-- Generated by Trae Work -->)
#   ├── assets/             (images, charts.js)
#   └── _shared/
#       ├── js/             (only JS libs referenced by HTML)
#       └── fonts/          (font files)

set -euo pipefail

REPORT_DIR="${1:-}"
OUTPUT_DIR="${2:-}"

if [[ -z "$REPORT_DIR" || -z "$OUTPUT_DIR" ]]; then
  echo "usage: deploy.sh <report-dir> <output-dir>" >&2
  exit 1
fi

# Resolve report dir
if [[ "$REPORT_DIR" != /* ]]; then
  REPORT_DIR="$PWD/$REPORT_DIR"
fi
REPORT_DIR="${REPORT_DIR%/}"

# Verify report dir has at least one HTML file
HTML_COUNT=$(find "$REPORT_DIR" -maxdepth 1 -name '*.html' | wc -l | tr -d ' ')
if [[ "$HTML_COUNT" -eq 0 ]]; then
  echo "error: no .html file found in $REPORT_DIR" >&2
  exit 1
fi

REPORT_NAME="$(basename "$REPORT_DIR")"
TARGET_DIR="$OUTPUT_DIR/$REPORT_NAME"

# --- Copy entire report directory ---
rm -rf "$TARGET_DIR"
cp -r "$REPORT_DIR" "$TARGET_DIR"

# --- Remove .md files (safety net) ---
find "$TARGET_DIR" -name '*.md' -delete 2>/dev/null || true

# --- Remove unreferenced JS from _shared/js/ ---
if [[ -d "$TARGET_DIR/_shared/js" ]]; then
  for js_file in "$TARGET_DIR/_shared/js/"*.js; do
    [[ -f "$js_file" ]] || continue
    js_name="$(basename "$js_file")"
    # Check if any HTML file references this JS
    if ! grep -rq "$js_name" "$TARGET_DIR/"*.html 2>/dev/null; then
      rm -f "$js_file"
    fi
  done
fi

# --- Verify HTML files have the required comment ---
MISSING_COMMENT=()
while IFS= read -r html_file; do
  if ! head -n 1 "$html_file" | grep -qF "<!-- Generated by Trae Work -->"; then
    MISSING_COMMENT+=("$(basename "$html_file")")
  fi
done < <(find "$TARGET_DIR" -maxdepth 1 -name '*.html')

if [[ ${#MISSING_COMMENT[@]} -gt 0 ]]; then
  echo "⚠ WARNING: The following HTML files are missing '<!-- Generated by Trae Work -->' on line 1:" >&2
  for f in "${MISSING_COMMENT[@]}"; do
    echo "  - $f" >&2
  done
  echo "  Deploy continues, but these files may not be recognized as report outputs." >&2
fi

# --- Summary ---
ASSET_COUNT=$(find "$TARGET_DIR/assets" -type f 2>/dev/null | wc -l | tr -d ' ')
FONT_COUNT=$(find "$TARGET_DIR/_shared/fonts" -type f 2>/dev/null | wc -l | tr -d ' ')
JS_COUNT=$(find "$TARGET_DIR/_shared/js" -type f 2>/dev/null | wc -l | tr -d ' ')
HTML_DEPLOYED=$(find "$TARGET_DIR" -maxdepth 1 -name '*.html' | wc -l | tr -d ' ')

echo "✔ Deployed to: $TARGET_DIR"
echo "  ${HTML_DEPLOYED} HTML file(s) + ${ASSET_COUNT} asset(s) + ${JS_COUNT} JS lib(s) + ${FONT_COUNT} font(s)"
