# html-deck :: deploy.ps1 — deploy deck to user's workspace
#
# Usage:
#   deploy.ps1 <deck-dir> <output-dir>
#
# Copies <deck-dir> into <output-dir>/<name>/, then:
#   1. Removes any .md files (plan.md etc. should not be delivered)
#   2. Removes unreferenced theme CSS from _shared/themes/
#   3. Removes unreferenced fx JS from _shared/animations/fx/
#   4. Removes unreferenced top-level JS/CSS from _shared/ (if not used by any HTML)
#   5. Verifies all .html files contain <!-- Generated by Trae Work -->
#
# Output structure:
#   <output-dir>/<name>/
#   ├── <name>.html         (must contain <!-- Generated by Trae Work -->)
#   ├── assets/             (images, chart JS)
#   └── _shared/
#       ├── base.css
#       ├── fonts.css
#       ├── decorations.css
#       ├── runtime.js
#       ├── echarts.min.js
#       ├── echarts-theme-sync.js
#       ├── animations/
#       │   ├── animations.css
#       │   ├── fx-runtime.js
#       │   └── fx/*.js
#       └── themes/*.css

param(
    [string]$DeckDir,
    [string]$OutputDir
)

if (-not $DeckDir -or -not $OutputDir) {
    Write-Error "usage: deploy.ps1 <deck-dir> <output-dir>"
    exit 1
}

# Resolve deck dir to absolute path
if (-not [System.IO.Path]::IsPathRooted($DeckDir)) {
    $DeckDir = Join-Path (Get-Location) $DeckDir
}
$DeckDir = $DeckDir.TrimEnd('\', '/')

# Verify deck dir has at least one HTML file
$htmlFiles = Get-ChildItem -Path $DeckDir -Filter "*.html" -File -ErrorAction SilentlyContinue
if (-not $htmlFiles -or $htmlFiles.Count -eq 0) {
    Write-Error "error: no .html file found in $DeckDir"
    exit 1
}

$DeckName = Split-Path -Leaf $DeckDir
$TargetDir = Join-Path $OutputDir $DeckName

# --- Copy entire deck directory ---
if (Test-Path $TargetDir) {
    Remove-Item -Recurse -Force $TargetDir
}
Copy-Item -Recurse -Path $DeckDir -Destination $TargetDir

# --- Remove .md files (plan.md etc.) ---
Get-ChildItem -Path $TargetDir -Filter "*.md" -Recurse -File -ErrorAction SilentlyContinue | Remove-Item -Force

# --- Collect all HTML content for reference checks ---
$allHtml = ""
Get-ChildItem -Path $TargetDir -Filter "*.html" -File | ForEach-Object {
    $allHtml += [System.IO.File]::ReadAllText($_.FullName)
}

# --- Remove unreferenced themes from _shared\themes\ ---
$themesDir = Join-Path $TargetDir "_shared\themes"
if (Test-Path $themesDir) {
    Get-ChildItem -Path $themesDir -Filter "*.css" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if (-not $allHtml.Contains($_.Name)) {
            Remove-Item -Force $_.FullName
        }
    }
}

# --- Remove unreferenced fx from _shared\animations\fx\ ---
$fxDir = Join-Path $TargetDir "_shared\animations\fx"
if (Test-Path $fxDir) {
    Get-ChildItem -Path $fxDir -Filter "*.js" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if (-not $allHtml.Contains($_.Name)) {
            Remove-Item -Force $_.FullName
        }
    }
}

# --- Remove unreferenced top-level _shared\ files ---
$sharedDir = Join-Path $TargetDir "_shared"
if (Test-Path $sharedDir) {
    Get-ChildItem -Path $sharedDir -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -in @(".css", ".js") } |
        ForEach-Object {
            if (-not $allHtml.Contains($_.Name)) {
                Remove-Item -Force $_.FullName
            }
        }
    # Also check animations base files
    $animDir = Join-Path $TargetDir "_shared\animations"
    if (Test-Path $animDir) {
        Get-ChildItem -Path $animDir -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Extension -in @(".css", ".js") } |
            ForEach-Object {
                if (-not $allHtml.Contains($_.Name)) {
                    Remove-Item -Force $_.FullName
                }
            }
    }
}

# --- Remove empty directories ---
if (Test-Path $sharedDir) {
    Get-ChildItem -Path $sharedDir -Directory -Recurse |
        Sort-Object { $_.FullName.Length } -Descending |
        Where-Object { (Get-ChildItem -Path $_.FullName -Force).Count -eq 0 } |
        ForEach-Object { Remove-Item -Force $_.FullName }
}

# --- Verify HTML files have the required comment ---
$missingComment = @()
Get-ChildItem -Path $TargetDir -Filter "*.html" -File | ForEach-Object {
    $firstLine = (Get-Content $_.FullName -TotalCount 1) -join ""
    if (-not $firstLine.Contains("<!-- Generated by Trae Work -->")) {
        $missingComment += $_.Name
    }
}

if ($missingComment.Count -gt 0) {
    Write-Warning "The following HTML files are missing '<!-- Generated by Trae Work -->' on line 1:"
    foreach ($f in $missingComment) {
        Write-Host "  - $f" -ForegroundColor Yellow
    }
    Write-Host "  Deploy continues, but these files may not be recognized as deck outputs." -ForegroundColor Yellow
}

# --- Summary ---
$assetCount = (Get-ChildItem -Path (Join-Path $TargetDir "assets") -File -Recurse -ErrorAction SilentlyContinue | Measure-Object).Count
$themeCount = (Get-ChildItem -Path (Join-Path $TargetDir "_shared\themes") -File -ErrorAction SilentlyContinue | Measure-Object).Count
$fxCount = (Get-ChildItem -Path (Join-Path $TargetDir "_shared\animations\fx") -File -ErrorAction SilentlyContinue | Measure-Object).Count
$htmlDeployed = (Get-ChildItem -Path $TargetDir -Filter "*.html" -File | Measure-Object).Count

Write-Host "OK Deployed to: $TargetDir"
Write-Host "  $htmlDeployed HTML file(s) + $assetCount asset(s) + $themeCount theme(s) + $fxCount fx script(s)"
