#!/usr/bin/env bash
# html-deck :: deploy.sh — deploy deck to user's workspace
#
# Usage:
#   deploy.sh <deck-dir> <output-dir>
#
# Copies <deck-dir> into <output-dir>/<name>/, then:
#   1. Removes any .md files (plan.md etc. should not be delivered)
#   2. Removes unreferenced theme CSS from _shared/themes/
#   3. Removes unreferenced fx JS from _shared/animations/fx/
#   4. Removes unreferenced top-level JS/CSS from _shared/ (if not used by any HTML)
#   5. Verifies all .html files contain <!-- Generated by Trae Work -->
#
# Output structure:
#   <output-dir>/<name>/
#   ├── <name>.html         (must contain <!-- Generated by Trae Work -->)
#   ├── assets/             (images, chart JS)
#   └── _shared/
#       ├── base.css
#       ├── fonts.css
#       ├── decorations.css
#       ├── runtime.js
#       ├── echarts.min.js
#       ├── echarts-theme-sync.js
#       ├── animations/
#       │   ├── animations.css
#       │   ├── fx-runtime.js
#       │   └── fx/*.js
#       └── themes/*.css

set -euo pipefail

DECK_DIR="${1:-}"
OUTPUT_DIR="${2:-}"

if [[ -z "$DECK_DIR" || -z "$OUTPUT_DIR" ]]; then
  echo "usage: deploy.sh <deck-dir> <output-dir>" >&2
  exit 1
fi

# Resolve deck dir
if [[ "$DECK_DIR" != /* ]]; then
  DECK_DIR="$PWD/$DECK_DIR"
fi
DECK_DIR="${DECK_DIR%/}"

# Verify deck dir has at least one HTML file
HTML_COUNT=$(find "$DECK_DIR" -maxdepth 1 -name '*.html' | wc -l | tr -d ' ')
if [[ "$HTML_COUNT" -eq 0 ]]; then
  echo "error: no .html file found in $DECK_DIR" >&2
  exit 1
fi

DECK_NAME="$(basename "$DECK_DIR")"
TARGET_DIR="$OUTPUT_DIR/$DECK_NAME"

# --- Copy entire deck directory ---
rm -rf "$TARGET_DIR"
cp -r "$DECK_DIR" "$TARGET_DIR"

# --- Remove .md files (plan.md etc.) ---
find "$TARGET_DIR" -name '*.md' -delete 2>/dev/null || true

# --- Collect all HTML content for reference checks ---
ALL_HTML=""
while IFS= read -r html_file; do
  ALL_HTML+="$(cat "$html_file")"
done < <(find "$TARGET_DIR" -maxdepth 1 -name '*.html')

# --- Remove unreferenced themes from _shared/themes/ ---
if [[ -d "$TARGET_DIR/_shared/themes" ]]; then
  for css_file in "$TARGET_DIR/_shared/themes/"*.css; do
    [[ -f "$css_file" ]] || continue
    css_name="$(basename "$css_file")"
    if ! echo "$ALL_HTML" | grep -qF "$css_name"; then
      rm -f "$css_file"
    fi
  done
fi

# --- Remove unreferenced fx from _shared/animations/fx/ ---
if [[ -d "$TARGET_DIR/_shared/animations/fx" ]]; then
  for js_file in "$TARGET_DIR/_shared/animations/fx/"*.js; do
    [[ -f "$js_file" ]] || continue
    js_name="$(basename "$js_file")"
    if ! echo "$ALL_HTML" | grep -qF "$js_name"; then
      rm -f "$js_file"
    fi
  done
fi

# --- Remove unreferenced top-level _shared/ files ---
if [[ -d "$TARGET_DIR/_shared" ]]; then
  for shared_file in "$TARGET_DIR/_shared/"*.{css,js}; do
    [[ -f "$shared_file" ]] || continue
    shared_name="$(basename "$shared_file")"
    if ! echo "$ALL_HTML" | grep -qF "$shared_name"; then
      rm -f "$shared_file"
    fi
  done
  # Also check animations base files
  for anim_file in "$TARGET_DIR/_shared/animations/"*.{css,js}; do
    [[ -f "$anim_file" ]] || continue
    anim_name="$(basename "$anim_file")"
    if ! echo "$ALL_HTML" | grep -qF "$anim_name"; then
      rm -f "$anim_file"
    fi
  done
fi

# --- Remove empty directories ---
find "$TARGET_DIR/_shared" -type d -empty -delete 2>/dev/null || true

# --- Verify HTML files have the required comment ---
MISSING_COMMENT=()
while IFS= read -r html_file; do
  if ! head -n 1 "$html_file" | grep -qF "<!-- Generated by Trae Work -->"; then
    MISSING_COMMENT+=("$(basename "$html_file")")
  fi
done < <(find "$TARGET_DIR" -maxdepth 1 -name '*.html')

if [[ ${#MISSING_COMMENT[@]} -gt 0 ]]; then
  echo "⚠ WARNING: The following HTML files are missing '<!-- Generated by Trae Work -->' on line 1:" >&2
  for f in "${MISSING_COMMENT[@]}"; do
    echo "  - $f" >&2
  done
  echo "  Deploy continues, but these files may not be recognized as deck outputs." >&2
fi

# --- Summary ---
ASSET_COUNT=$(find "$TARGET_DIR/assets" -type f 2>/dev/null | wc -l | tr -d ' ')
THEME_COUNT=$(find "$TARGET_DIR/_shared/themes" -type f 2>/dev/null | wc -l | tr -d ' ')
FX_COUNT=$(find "$TARGET_DIR/_shared/animations/fx" -type f 2>/dev/null | wc -l | tr -d ' ')
HTML_DEPLOYED=$(find "$TARGET_DIR" -maxdepth 1 -name '*.html' | wc -l | tr -d ' ')

echo "✔ Deployed to: $TARGET_DIR"
echo "  ${HTML_DEPLOYED} HTML file(s) + ${ASSET_COUNT} asset(s) + ${THEME_COUNT} theme(s) + ${FX_COUNT} fx script(s)"
