# html-deck :: deploy.ps1 — deploy deck to user's workspace
#
# Usage:
#   deploy.ps1 <deck-dir> <output-dir>
#
# Copies <deck-dir> into <output-dir>/<name>/, then:
#   1. Removes any .md files (plan.md etc. should not be delivered)
#   2. Removes unreferenced theme CSS from _shared/themes/
#   3. Removes unreferenced fx JS from _shared/animations/fx/
#   4. Removes unreferenced top-level JS/CSS from _shared/ (if not used by any HTML)
#   5. Verifies all .html files contain <!-- Generated by Trae Work -->

param(
    [Parameter(Position=0)]
    [string]$DeckDir,
    [Parameter(Position=1)]
    [string]$OutputDir
)

$ErrorActionPreference = "Stop"

if (-not $DeckDir -or -not $OutputDir) {
    Write-Error "usage: deploy.ps1 <deck-dir> <output-dir>"
    exit 1
}

# Resolve deck dir
if (-not [System.IO.Path]::IsPathRooted($DeckDir)) {
    $DeckDir = Join-Path $PWD $DeckDir
}
$DeckDir = $DeckDir.TrimEnd('\', '/')

# Verify deck dir has at least one HTML file
$htmlFiles = Get-ChildItem -Path $DeckDir -Filter "*.html" -File -ErrorAction SilentlyContinue
if (-not $htmlFiles -or $htmlFiles.Count -eq 0) {
    Write-Error "error: no .html file found in $DeckDir"
    exit 1
}

$DeckName = Split-Path -Leaf $DeckDir
$TargetDir = Join-Path $OutputDir $DeckName

# --- Copy entire deck directory ---
if (Test-Path $TargetDir) {
    Remove-Item -Recurse -Force $TargetDir
}
Copy-Item -Recurse -Path $DeckDir -Destination $TargetDir

# --- Remove .md files (plan.md etc.) ---
Get-ChildItem -Path $TargetDir -Filter "*.md" -Recurse -File -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue

# --- Collect all HTML content for reference checks ---
$AllHtml = ""
Get-ChildItem -Path $TargetDir -Filter "*.html" -File | ForEach-Object {
    $AllHtml += Get-Content $_.FullName -Raw
}

# --- Remove unreferenced themes from _shared/themes/ ---
$themesDir = Join-Path $TargetDir "_shared/themes"
if (Test-Path $themesDir) {
    Get-ChildItem -Path $themesDir -Filter "*.css" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if ($AllHtml -notlike "*$($_.Name)*") {
            Remove-Item $_.FullName -Force
        }
    }
}

# --- Remove unreferenced fx from _shared/animations/fx/ ---
$fxDir = Join-Path $TargetDir "_shared/animations/fx"
if (Test-Path $fxDir) {
    Get-ChildItem -Path $fxDir -Filter "*.js" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if ($AllHtml -notlike "*$($_.Name)*") {
            Remove-Item $_.FullName -Force
        }
    }
}

# --- Remove unreferenced top-level _shared/ files ---
$sharedDir = Join-Path $TargetDir "_shared"
if (Test-Path $sharedDir) {
    Get-ChildItem -Path $sharedDir -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -in @(".css", ".js") } |
        ForEach-Object {
            if ($AllHtml -notlike "*$($_.Name)*") {
                Remove-Item $_.FullName -Force
            }
        }

    # Also check animations base files
    $animDir = Join-Path $sharedDir "animations"
    if (Test-Path $animDir) {
        Get-ChildItem -Path $animDir -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Extension -in @(".css", ".js") } |
            ForEach-Object {
                if ($AllHtml -notlike "*$($_.Name)*") {
                    Remove-Item $_.FullName -Force
                }
            }
    }
}

# --- Remove empty directories ---
if (Test-Path (Join-Path $TargetDir "_shared")) {
    Get-ChildItem -Path (Join-Path $TargetDir "_shared") -Directory -Recurse |
        Sort-Object { $_.FullName.Length } -Descending |
        Where-Object { (Get-ChildItem $_.FullName -Force).Count -eq 0 } |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

# --- Verify HTML files have the required comment ---
$MissingComment = @()
Get-ChildItem -Path $TargetDir -Filter "*.html" -File | ForEach-Object {
    $firstLine = Get-Content $_.FullName -TotalCount 1
    if ($firstLine -notlike "*<!-- Generated by Trae Work -->*") {
        $MissingComment += $_.Name
    }
}

if ($MissingComment.Count -gt 0) {
    Write-Warning "The following HTML files are missing '<!-- Generated by Trae Work -->' on line 1:"
    foreach ($f in $MissingComment) {
        Write-Warning "  - $f"
    }
    Write-Warning "  Deploy continues, but these files may not be recognized as deck outputs."
}

# --- Summary ---
$assetDir = Join-Path $TargetDir "assets"
$AssetCount = if (Test-Path $assetDir) { (Get-ChildItem $assetDir -File -Recurse).Count } else { 0 }
$ThemeCount = if (Test-Path $themesDir) { (Get-ChildItem $themesDir -File -ErrorAction SilentlyContinue).Count } else { 0 }
$FxCount = if (Test-Path $fxDir) { (Get-ChildItem $fxDir -File -ErrorAction SilentlyContinue).Count } else { 0 }
$HtmlDeployed = (Get-ChildItem -Path $TargetDir -Filter "*.html" -File).Count

Write-Host "OK Deployed to: $TargetDir"
Write-Host "  $HtmlDeployed HTML file(s) + $AssetCount asset(s) + $ThemeCount theme(s) + $FxCount fx script(s)"
