# html-deck :: new-deck.ps1 — scaffold a new deck directory
#
# Usage:
#   new-deck.ps1 <name> <output-base-dir>
#
# Creates <output-base-dir>/<name>/ with:
#   <name>.html        (scaffold with <!-- Generated by Trae Work --> comment)
#   assets/            (for generated/downloaded images, chart JS)
#   _shared/           (minimal shared assets — model copies more as needed)

param(
    [Parameter(Position=0)]
    [string]$Name,
    [Parameter(Position=1)]
    [string]$BaseDir
)

$ErrorActionPreference = "Stop"

if (-not $Name -or -not $BaseDir) {
    Write-Error "usage: new-deck.ps1 <name> <output-base-dir>`n`n  <name>            Deck directory name (also used as HTML filename)`n  <output-base-dir> Directory where <name>/ will be created (your work dir)"
    exit 1
}

$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$Here = (Resolve-Path (Join-Path $ScriptDir "..")).Path

if (-not [System.IO.Path]::IsPathRooted($BaseDir)) {
    $BaseDir = Join-Path $PWD $BaseDir
}

$OutDir = Join-Path $BaseDir $Name

if (Test-Path $OutDir) {
    Write-Error "error: $OutDir already exists"
    exit 1
}

# --- Create directory structure ---
New-Item -ItemType Directory -Path (Join-Path $OutDir "assets") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OutDir "_shared/animations/fx") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OutDir "_shared/themes") -Force | Out-Null

# --- Copy minimal shared assets ---
$sharedFiles = @("base.css", "fonts.css", "decorations.css", "runtime.js", "echarts-theme-sync.js", "chart.umd.min.js")
foreach ($f in $sharedFiles) {
    $src = Join-Path $Here "assets/$f"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $OutDir "_shared/$f")
    }
}

# Copy highlight.js assets
$hljsDir = Join-Path $Here "assets/hljs"
if (Test-Path $hljsDir) {
    $hljsOut = Join-Path $OutDir "_shared/hljs"
    New-Item -ItemType Directory -Path $hljsOut -Force | Out-Null
    Copy-Item (Join-Path $hljsDir "*") $hljsOut
}

# Copy animations base files
$animFiles = @("animations.css", "fx-runtime.js")
foreach ($f in $animFiles) {
    $src = Join-Path $Here "assets/animations/$f"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $OutDir "_shared/animations/$f")
    }
}

# --- Generate scaffold HTML ---
$htmlContent = @'
<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN" data-theme="minimal-white">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Deck</title>
<link rel="stylesheet" href="./_shared/fonts.css">
<link rel="stylesheet" href="./_shared/base.css">
<link id="theme-link" rel="stylesheet" href="./_shared/themes/minimal-white.css">
<link rel="stylesheet" href="./_shared/animations/animations.css">
<!-- <link rel="stylesheet" href="./_shared/decorations.css"> -->
</head>
<body data-themes="minimal-white" data-theme-base="./_shared/themes/">
<div class="deck">

  <!-- 1. Cover -->
  <section class="slide" data-title="Cover">
    <p class="kicker">Deck · 2026</p>
    <h1 class="h1 anim-fade-up" data-anim="fade-up">Presentation Title</h1>
    <p class="lede">Subtitle goes here</p>
    <div class="deck-footer"><span class="dim2">Author</span><span class="slide-number" data-current="1" data-total="3"></span></div>
    <div class="notes">Speaker notes go here.</div>
  </section>

  <!-- 2. Content -->
  <section class="slide" data-title="Content">
    <p class="kicker">Section</p>
    <h2 class="h2">Slide Title</h2>
    <p>Content goes here.</p>
  </section>

  <!-- 3. Thanks -->
  <section class="slide center tc" data-title="Thanks">
    <h1 class="h1" style="font-size:160px;line-height:1"><span class="gradient-text">Thanks</span></h1>
  </section>

</div>
<script src="./_shared/runtime.js"></script>
<script src="./_shared/echarts-theme-sync.js"></script>
<!-- <script src="./_shared/animations/fx-runtime.js"></script> -->
</body></html>
'@

$htmlPath = Join-Path $OutDir "$Name.html"
[System.IO.File]::WriteAllText($htmlPath, $htmlContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "OK Created: $OutDir/$Name.html"
Write-Host "OK Created: $OutDir/assets/"
Write-Host "OK Created: $OutDir/_shared/ (base.css, fonts.css, runtime.js, animations/)"
Write-Host "OK Created: $OutDir/_shared/themes/ (copy needed themes here from $Here/assets/themes/)"
Write-Host "OK Created: $OutDir/_shared/animations/fx/ (copy needed fx here from $Here/assets/animations/fx/)"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Copy theme:  Copy-Item $Here/assets/themes/<theme>.css $OutDir/_shared/themes/"
Write-Host "  2. Copy fx:     Copy-Item $Here/assets/animations/fx/<effect>.js $OutDir/_shared/animations/fx/"
Write-Host "  3. Edit $Name.html - fill in theme, content, animations"
Write-Host "  4. Place images in $OutDir/assets/"
